yobo_lesser:
  groupSpawn: false
  groupAmount: 1
  spawnRate: 1.0
  worlds: []
  biomes:
  - PLAINS
  - FOREST
  - BIRCH_FOREST
  - BIRCH_FOREST_HILLS
  regions: []
yobo_greater:
  groupSpawn: false
  groupAmount: 1
  spawnRate: 1.0
  worlds: []
  biomes:
  - MUTATED_PLAINS
  - MUTATED_FOREST
  - MUTATED_BIRCH_FOREST
  - MUTATED_BIRCH_FOREST_HILLS
  regions: []
yobo_elite:
  groupSpawn: false
  groupAmount: 1
  spawnRate: 1.0
  worlds: []
  biomes:
  - EXTREME_HILLS
  - MUTATED_EXTREME_HILLS
  - ROOFED_FOREST
  - MUTATED_ROOFED_FOREST
  regions: []
yobo_brutal:
  groupSpawn: false
  groupAmount: 1
  spawnRate: 1.0
  worlds: []
  biomes:
  - EXTREME_HILLS
  - MUTATED_EXTREME_HILLS
  - EXTREME_HILLS_WITH_TREES
  - MUTATED_EXTREME_HILLS_WITH_TREES
  - SMALLER_EXTREME_HILLS
  regions: []
savage_lesser:
  groupSpawn: false
  groupAmount: 1
  spawnRate: 1.0
  worlds: []
  biomes:
  - DESERT
  - DESERT_HILLS
  - MUTATED_DESERT
  regions: []
savage_greater:
  groupSpawn: false
  groupAmount: 1
  spawnRate: 1.0
  worlds: []
  biomes:
  - SAVANNA
  - SAVANNA_ROCK
  - MUTATED_SAVANNA
  - MUTATED_SAVANNA_ROCK
  regions: []
savage_elite:
  groupSpawn: false
  groupAmount: 1
  spawnRate: 1.0
  worlds: []
  biomes:
  - MESA
  - MESA_ROCK
  - REDWOOD_TAIGA
  - MUTATED_REDWOOD_TAIGA
  regions: []
savage_brutal:
  groupSpawn: false
  groupAmount: 1
  spawnRate: 1.0
  worlds: []
  biomes:
  - MESA_CLEAR_ROCK
  - MUTATED_MESA_CLEAR_ROCK
  - REDWOOD_TAIGA_HILLS
  - MUTATED_REDWOOD_TAIGA_HILLS
  regions: []
ruffian_lesser:
  groupSpawn: false
  groupAmount: 1
  spawnRate: 1.0
  worlds: []
  biomes:
  - JUNGLE
  - JUNGLE_EDGE
  - MUTATED_JUNGLE_EDGE
  - SWAMPLAND
  regions: []
ruffian_greater:
  groupSpawn: false
  groupAmount: 1
  spawnRate: 1.0
  worlds: []
  biomes:
  - REDWOOD_TAIGA_HILLS
  - JUNGLE_HILLS
  regions: []
ruffian_elite:
  groupSpawn: false
  groupAmount: 1
  spawnRate: 1.0
  worlds: []
  biomes:
  - MUTATED_BIRCH_FOREST_HILLS
  - MUTATED_ROOFED_FOREST
  - MUSHROOM_ISLAND
  - MUTATED_JUNGLE_EDGE
  regions: []
ruffian_brutal:
  groupSpawn: false
  groupAmount: 1
  spawnRate: 1.0
  worlds: []
  biomes:
  - MUTATED_JUNGLE
  - MUTATED_SWAMPLAND
  - MUSHROOM_ISLAND_SHORE
  regions: []
behemoth_lesser:
  groupSpawn: false
  groupAmount: 1
  spawnRate: 1.0
  worlds: []
  biomes:
  - FROZEN_RIVER
  - FROZEN_OCEAN
  - COLD_BEACH
  - TAIGA_COLD
  regions: []
behemoth_greater:
  groupSpawn: false
  groupAmount: 1
  spawnRate: 1.0
  worlds: []
  biomes:
  - MUTATED_TAIGA_COLD
  regions: []
behemoth_elite:
  groupSpawn: false
  groupAmount: 1
  spawnRate: 1.0
  worlds: []
  biomes:
  - ICE_FLATS
  - ICE_MOUNTAINS
  regions: []
behemoth_brutal:
  groupSpawn: false
  groupAmount: 1
  spawnRate: 1.0
  worlds: []
  biomes:
  - MUTATED_ICE_FLATS
  regions: []
